import type { Property } from "../src/lib/types";

// Imóveis de referência — exemplos do desafio + demos adicionais.
export const properties: Property[] = [
  {
    code: "FLN001",
    name: "Apartamento Beira-Mar Florianópolis",
    propertyType: "Apartamento",
    bedroomQuantity: 2,
    bathroomQuantity: 1,
    guestCapacity: 4,
    address: {
      street: "Rua Lauro Linhares",
      number: "589",
      complement: "Apto 301",
      neighborhood: "Trindade",
      city: "Florianópolis",
      state: "SC",
      postalCode: "88036-001",
    },
    operational: {
      wifiNetwork: "SeaHome_FLN001",
      wifiPassword: "floripa2024",
      isSelfCheckin: true,
      propertyAccessType: "smart_lock",
      propertyAccessInstructions: "Use o código 4521 na fechadura eletrônica",
      propertyPassword: "4521",
      hasParkingSpot: true,
      parkingSpotIdentifier: "Vaga 12 — subsolo B1",
      parkingSpotInstructions: "Portão lateral, código 7890 no interfone",
    },
    rules: {
      checkInTime: "15:00",
      checkOutTime: "11:00",
      allowPet: false,
      smokingPermitted: false,
      suitableForChildren: true,
      suitableForBabies: true,
      eventsPermitted: false,
    },
    amenities: { wifi: true, tv: true, air_conditioning: true, kitchen: true, washing_machine: true, elevator: true, balcony: true },
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800"],
    host: { name: "Ana Paula", phone: "+5548991234567" },
  },
  {
    code: "GRM001",
    name: "Chalé Serra Gramado",
    propertyType: "Casa",
    bedroomQuantity: 3,
    bathroomQuantity: 2,
    guestCapacity: 6,
    address: {
      street: "Rua das Hortênsias",
      number: "220",
      complement: null,
      neighborhood: "Planalto",
      city: "Gramado",
      state: "RS",
      postalCode: "95670-000",
    },
    operational: {
      wifiNetwork: "ChaletSerra_GRM",
      wifiPassword: "gramado@2024",
      isSelfCheckin: false,
      propertyAccessType: "keybox",
      propertyAccessInstructions: "A chave está no cofre na entrada. Código: 1983",
      propertyPassword: "1983",
      hasParkingSpot: true,
      parkingSpotIdentifier: null,
      parkingSpotInstructions: "Garagem própria para 2 carros",
    },
    rules: {
      checkInTime: "14:00",
      checkOutTime: "12:00",
      allowPet: true,
      smokingPermitted: false,
      suitableForChildren: true,
      suitableForBabies: false,
      eventsPermitted: false,
    },
    amenities: { wifi: true, tv: true, kitchen: true, bbq_grill: true, balcony: true, dishwasher: true },
    images: ["https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800"],
    host: { name: "Carlos Eduardo", phone: "+5554998765432" },
  },
  {
    code: "BUZ001",
    name: "Suíte Búzios Pé na Areia",
    propertyType: "Apartamento",
    bedroomQuantity: 1,
    bathroomQuantity: 1,
    guestCapacity: 2,
    address: {
      street: "Rua das Pedras",
      number: "110",
      complement: "Suíte 5",
      neighborhood: "Centro",
      city: "Búzios",
      state: "RJ",
      postalCode: "28950-000",
    },
    operational: {
      wifiNetwork: "BuziosBeach_5G",
      wifiPassword: "buzios2025",
      isSelfCheckin: true,
      propertyAccessType: "smart_lock",
      propertyAccessInstructions: "Código 3312 na fechadura da porta",
      propertyPassword: "3312",
      hasParkingSpot: false,
      parkingSpotIdentifier: null,
      parkingSpotInstructions: null,
    },
    rules: {
      checkInTime: "14:00",
      checkOutTime: "11:00",
      allowPet: false,
      smokingPermitted: false,
      suitableForChildren: false,
      suitableForBabies: false,
      eventsPermitted: false,
    },
    amenities: { wifi: true, tv: true, air_conditioning: true, kitchen: true, pool: true },
    images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"],
    host: { name: "Mariana Costa", phone: "+5522997654321" },
  },
  {
    code: "SAL001",
    name: "Studio Pelourinho Salvador",
    propertyType: "Estúdio",
    bedroomQuantity: 1,
    bathroomQuantity: 1,
    guestCapacity: 2,
    address: {
      street: "Ladeira do Carmo",
      number: "45",
      complement: "Apto 2",
      neighborhood: "Pelourinho",
      city: "Salvador",
      state: "BA",
      postalCode: "40025-010",
    },
    operational: {
      wifiNetwork: "PeloStudio_WiFi",
      wifiPassword: "salvador#321",
      isSelfCheckin: true,
      propertyAccessType: "keybox",
      propertyAccessInstructions: "Cofre na grade. Código 7744",
      propertyPassword: "7744",
      hasParkingSpot: false,
      parkingSpotIdentifier: null,
      parkingSpotInstructions: null,
    },
    rules: {
      checkInTime: "13:00",
      checkOutTime: "11:00",
      allowPet: false,
      smokingPermitted: false,
      suitableForChildren: true,
      suitableForBabies: false,
      eventsPermitted: false,
    },
    amenities: { wifi: true, tv: true, air_conditioning: true, kitchen: true },
    images: ["https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800"],
    host: { name: "Jorge Mendes", phone: "+5571996543210" },
  },
  {
    code: "NAT001",
    name: "Cobertura Dunas Natal",
    propertyType: "Apartamento",
    bedroomQuantity: 3,
    bathroomQuantity: 2,
    guestCapacity: 6,
    address: {
      street: "Av. Engenheiro Roberto Freire",
      number: "2790",
      complement: "Cobertura 01",
      neighborhood: "Ponta Negra",
      city: "Natal",
      state: "RN",
      postalCode: "59090-300",
    },
    operational: {
      wifiNetwork: "DunasNatal_Home",
      wifiPassword: "natal@dunas",
      isSelfCheckin: true,
      propertyAccessType: "smart_lock",
      propertyAccessInstructions: "App Smart Lock ou código 9901",
      propertyPassword: "9901",
      hasParkingSpot: true,
      parkingSpotIdentifier: "Cobertura 01",
      parkingSpotInstructions: "2 vagas cobertas no subsolo",
    },
    rules: {
      checkInTime: "15:00",
      checkOutTime: "12:00",
      allowPet: true,
      smokingPermitted: false,
      suitableForChildren: true,
      suitableForBabies: true,
      eventsPermitted: false,
    },
    amenities: { wifi: true, tv: true, air_conditioning: true, kitchen: true, pool: true, balcony: true, bbq_grill: true },
    images: ["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800"],
    host: { name: "Fernanda Lima", phone: "+5584998870001" },
  },
  {
    code: "FOR001",
    name: "Apartamento Vista Mar Fortaleza",
    propertyType: "Apartamento",
    bedroomQuantity: 2,
    bathroomQuantity: 1,
    guestCapacity: 4,
    address: {
      street: "Av. Beira Mar",
      number: "3800",
      complement: "Apto 802",
      neighborhood: "Meireles",
      city: "Fortaleza",
      state: "CE",
      postalCode: "60165-121",
    },
    operational: {
      wifiNetwork: "BeiraMar_FRT",
      wifiPassword: "fortaleza2025",
      isSelfCheckin: false,
      propertyAccessType: "key",
      propertyAccessInstructions: "Chave com o porteiro. Apresente o nome Seazone",
      propertyPassword: null,
      hasParkingSpot: true,
      parkingSpotIdentifier: "Vaga 22",
      parkingSpotInstructions: "Subsolo — acesso pelo portão lateral",
    },
    rules: {
      checkInTime: "14:00",
      checkOutTime: "11:00",
      allowPet: false,
      smokingPermitted: false,
      suitableForChildren: true,
      suitableForBabies: true,
      eventsPermitted: false,
    },
    amenities: { wifi: true, tv: true, air_conditioning: true, kitchen: true, balcony: true, elevator: true },
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800"],
    host: { name: "Roberto Alves", phone: "+5585997001122" },
  },
  {
    code: "PDG001",
    name: "Casa Porto de Galinhas",
    propertyType: "Casa",
    bedroomQuantity: 4,
    bathroomQuantity: 3,
    guestCapacity: 8,
    address: {
      street: "Rua Beijupirá",
      number: "78",
      complement: null,
      neighborhood: "Porto de Galinhas",
      city: "Ipojuca",
      state: "PE",
      postalCode: "55590-000",
    },
    operational: {
      wifiNetwork: "CasaPDG_5G",
      wifiPassword: "galinhas2025",
      isSelfCheckin: true,
      propertyAccessType: "keybox",
      propertyAccessInstructions: "Cofre na entrada. Código 5566",
      propertyPassword: "5566",
      hasParkingSpot: true,
      parkingSpotIdentifier: null,
      parkingSpotInstructions: "Área de estacionamento para 3 carros",
    },
    rules: {
      checkInTime: "15:00",
      checkOutTime: "11:00",
      allowPet: false,
      smokingPermitted: false,
      suitableForChildren: true,
      suitableForBabies: true,
      eventsPermitted: false,
    },
    amenities: { wifi: true, tv: true, air_conditioning: true, kitchen: true, pool: true, bbq_grill: true, balcony: true },
    images: ["https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800"],
    host: { name: "Patrícia Souza", phone: "+5581997223344" },
  },
  {
    code: "CPJ001",
    name: "Chalé Campos do Jordão",
    propertyType: "Casa",
    bedroomQuantity: 2,
    bathroomQuantity: 1,
    guestCapacity: 4,
    address: {
      street: "Rua Delfim Moreira",
      number: "350",
      complement: null,
      neighborhood: "Abernéssia",
      city: "Campos do Jordão",
      state: "SP",
      postalCode: "12460-000",
    },
    operational: {
      wifiNetwork: "Chalet_CJordao",
      wifiPassword: "serragrande1",
      isSelfCheckin: false,
      propertyAccessType: "key",
      propertyAccessInstructions: "Anfitrião entregará a chave no check-in",
      propertyPassword: null,
      hasParkingSpot: true,
      parkingSpotIdentifier: null,
      parkingSpotInstructions: "Garagem coberta para 1 carro",
    },
    rules: {
      checkInTime: "14:00",
      checkOutTime: "12:00",
      allowPet: true,
      smokingPermitted: false,
      suitableForChildren: true,
      suitableForBabies: false,
      eventsPermitted: false,
    },
    amenities: { wifi: true, tv: true, kitchen: true, bbq_grill: true, balcony: true },
    images: ["https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800"],
    host: { name: "Luísa Ferreira", phone: "+5512998001234" },
  },
  {
    code: "RIO001",
    name: "Loft Ipanema Rio de Janeiro",
    propertyType: "Loft",
    bedroomQuantity: 1,
    bathroomQuantity: 1,
    guestCapacity: 2,
    address: {
      street: "Rua Visconde de Pirajá",
      number: "414",
      complement: "Loft 7",
      neighborhood: "Ipanema",
      city: "Rio de Janeiro",
      state: "RJ",
      postalCode: "22410-002",
    },
    operational: {
      wifiNetwork: "IpaLoft_WiFi",
      wifiPassword: "ipanema@rio",
      isSelfCheckin: true,
      propertyAccessType: "smart_lock",
      propertyAccessInstructions: "Código 2277 na fechadura digital",
      propertyPassword: "2277",
      hasParkingSpot: false,
      parkingSpotIdentifier: null,
      parkingSpotInstructions: null,
    },
    rules: {
      checkInTime: "15:00",
      checkOutTime: "11:00",
      allowPet: false,
      smokingPermitted: false,
      suitableForChildren: false,
      suitableForBabies: false,
      eventsPermitted: false,
    },
    amenities: { wifi: true, tv: true, air_conditioning: true, kitchen: true, elevator: true },
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
    host: { name: "Beatriz Ramos", phone: "+5521996554433" },
  },
  {
    code: "MCO001",
    name: "Bangalô Praia de Pajuçara",
    propertyType: "Casa",
    bedroomQuantity: 2,
    bathroomQuantity: 1,
    guestCapacity: 4,
    address: {
      street: "Av. Dr. Antônio Gouveia",
      number: "1200",
      complement: null,
      neighborhood: "Pajuçara",
      city: "Maceió",
      state: "AL",
      postalCode: "57030-000",
    },
    operational: {
      wifiNetwork: "PajucaraWifi",
      wifiPassword: "maceio#praia",
      isSelfCheckin: true,
      propertyAccessType: "keybox",
      propertyAccessInstructions: "Cofre na varanda. Código 8800",
      propertyPassword: "8800",
      hasParkingSpot: true,
      parkingSpotIdentifier: null,
      parkingSpotInstructions: "Quintal com espaço para 2 carros",
    },
    rules: {
      checkInTime: "14:00",
      checkOutTime: "11:00",
      allowPet: true,
      smokingPermitted: false,
      suitableForChildren: true,
      suitableForBabies: true,
      eventsPermitted: false,
    },
    amenities: { wifi: true, tv: true, air_conditioning: true, kitchen: true, bbq_grill: true },
    images: ["https://images.unsplash.com/photo-1551524559-8af4e6624178?w=800"],
    host: { name: "Tiago Barros", phone: "+5582998765000" },
  },
  {
    code: "ARR001",
    name: "Pousada Arraial d'Ajuda",
    propertyType: "Casa",
    bedroomQuantity: 2,
    bathroomQuantity: 2,
    guestCapacity: 4,
    address: {
      street: "Rua do Mucugê",
      number: "88",
      complement: null,
      neighborhood: "Centro",
      city: "Porto Seguro",
      state: "BA",
      postalCode: "45810-000",
    },
    operational: {
      wifiNetwork: "ArrialHome_5G",
      wifiPassword: "arraial2025!",
      isSelfCheckin: false,
      propertyAccessType: "key",
      propertyAccessInstructions: "Chave com a anfitrião. Contato no WhatsApp",
      propertyPassword: null,
      hasParkingSpot: true,
      parkingSpotIdentifier: null,
      parkingSpotInstructions: "Estacionamento na rua",
    },
    rules: {
      checkInTime: "13:00",
      checkOutTime: "11:00",
      allowPet: false,
      smokingPermitted: false,
      suitableForChildren: true,
      suitableForBabies: false,
      eventsPermitted: false,
    },
    amenities: { wifi: true, tv: true, air_conditioning: true, kitchen: true, pool: true },
    images: ["https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800"],
    host: { name: "Claudia Neves", phone: "+5573997001234" },
  },
  {
    code: "BON001",
    name: "Eco Lodge Bonito MS",
    propertyType: "Casa",
    bedroomQuantity: 2,
    bathroomQuantity: 1,
    guestCapacity: 4,
    address: {
      street: "Rua Coronel Pilad Rebuá",
      number: "1780",
      complement: null,
      neighborhood: "Centro",
      city: "Bonito",
      state: "MS",
      postalCode: "79290-000",
    },
    operational: {
      wifiNetwork: "EcoLodge_BON",
      wifiPassword: "bonito@eco",
      isSelfCheckin: true,
      propertyAccessType: "keybox",
      propertyAccessInstructions: "Cofre na entrada. Código 4433",
      propertyPassword: "4433",
      hasParkingSpot: true,
      parkingSpotIdentifier: null,
      parkingSpotInstructions: "Área externa para 2 carros",
    },
    rules: {
      checkInTime: "14:00",
      checkOutTime: "10:00",
      allowPet: false,
      smokingPermitted: false,
      suitableForChildren: true,
      suitableForBabies: false,
      eventsPermitted: false,
    },
    amenities: { wifi: true, tv: true, kitchen: true, bbq_grill: true, balcony: true },
    images: ["https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800"],
    host: { name: "Anderson Matos", phone: "+5567998001111" },
  },
  {
    code: "PIR001",
    name: "Casa Colonial Pirenópolis",
    propertyType: "Casa",
    bedroomQuantity: 3,
    bathroomQuantity: 2,
    guestCapacity: 6,
    address: {
      street: "Rua do Rosário",
      number: "55",
      complement: null,
      neighborhood: "Centro Histórico",
      city: "Pirenópolis",
      state: "GO",
      postalCode: "72980-000",
    },
    operational: {
      wifiNetwork: "ColonialPiren_WiFi",
      wifiPassword: "pirenopolis1",
      isSelfCheckin: false,
      propertyAccessType: "key",
      propertyAccessInstructions: "Chave com a vizinha Dona Maria (n° 53)",
      propertyPassword: null,
      hasParkingSpot: true,
      parkingSpotIdentifier: null,
      parkingSpotInstructions: "Garagem para 2 carros",
    },
    rules: {
      checkInTime: "15:00",
      checkOutTime: "12:00",
      allowPet: true,
      smokingPermitted: false,
      suitableForChildren: true,
      suitableForBabies: true,
      eventsPermitted: true,
    },
    amenities: { wifi: true, tv: true, kitchen: true, bbq_grill: true, balcony: true, washing_machine: true },
    images: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800"],
    host: { name: "Renata Gomes", phone: "+5562997880099" },
  },
];
